spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 12345678
    driverClassName: org.postgresql.Driver